# Generated by Django 6.0.2 on 2026-02-09 01:49

from django.db import migrations


def create_categories(apps, schema_editor):
    BlogCategory = apps.get_model('home', 'BlogCategory')
    categories = [
        {
            'name': 'Viajes',
            'slug': 'viajes',
            'description': 'Experiencias de viaje y destinos',
            'color': '#10B981'
        },
        {
            'name': 'Tecnología',
            'slug': 'tecnologia',
            'description': 'Programación, gadgets, software',
            'color': '#3B82F6'
        },
        {
            'name': 'Hablemos de Trenes',
            'slug': 'trenes',
            'description': 'Ferrocarriles, historia, rutas',
            'color': '#F59E0B'
        },
        {
            'name': 'Otros',
            'slug': 'otros',
            'description': 'Temas variados',
            'color': '#6B7280'
        },
    ]
    for cat in categories:
        BlogCategory.objects.create(**cat)


def delete_categories(apps, schema_editor):
    BlogCategory = apps.get_model('home', 'BlogCategory')
    BlogCategory.objects.filter(
        slug__in=['viajes', 'tecnologia', 'trenes', 'otros']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_add_blog_models'),
    ]

    operations = [
        migrations.RunPython(create_categories, delete_categories),
    ]
